### ISSUE TITLE
Hyperlinks in the page not redirected properly

### ISSUE THREAD

**Issue by rishabh-me** [akash-me/akash-me.github.io#4]
The hyperlinks on the top of the home page should lead to the heading tiles. However, they go a little too low on the page and the heading tile is hidden and the content of that heading starts. It should stop at the heading tile being visible at the top of the current page/screen.

**Comment by akash-me** [comment]
I changed like that so specific content will visible to the user. Like if anyone clicks on the project then only projects will visible. If it goes to title only then some cards may partially visible.
